### ISSUE TITLE
AAD authencation is not working when upgraded to SonarQube v7.9.1 LTS version 

### ISSUE THREAD

**Issue by v-haburr** [hkamel/sonar-auth-aad#74] opened 2019-07-12 06:52 UTC
we tried using sonar-auth-aad-plugin-1.1 and sonar-auth-aad-plugin-1.1-RC2 to authenticate our sonar portal which is upgraded to SonarQube v7.9.1 LTS version but unable to authenticate and thrown below error shown in screenshot
![error](https://user-images.githubusercontent.com/52814024/61108128-26401500-a49f-11e9-9013-82aa413ba665.jpg)

**What we observed is**
•	Sonar7.9 LTS version has a prerequisite to have Java 11+.
•	We tried installing jdk-11.0.3 version where sonar service is unable to start and still looks for 11x above version so we installed latest java version (jdk-12.0.1).  Where Sonarqube7.9.1 LTS service started successfully.
•	After migrating the DB and modifying all necessary values for sonar-auth-aad-plugin-1.1-RC2 in administration tab and tried login with AAD but it  is not working . we are getting unauthorized exception.
•	So we tried running previous versions 7.8/7.7 with jdk-12.0.1 which also faces same error while logging with AAD.
•	Reverted the java version to previous version (jdk1.8.0_131) and tried logging with AAD for SQ versions 7.8/7.7 which are working as expected.

In a glimpse the error is unable to login with AAD plugin with latest java version which is a prerequisite for SonarQube 7.9.1 LTS version.

Please suggest on how to proceed.

**Comment by julienlancelot** [comment] 2019-07-12 07:49
Hi,

In order to understand what is the error, could you please : 
- Active DEBUG log : set "sonar.debug.level" to DEBUG in conf/sonar.properties
- Try again to login and add the generated logs in the issue you've raised

Regards

**Comment by v-haburr** [comment] 2019-07-12 09:21
Hi,

As pointed, below are the DEBUG  logs
[Logs.zip](https://github.com/hkamel/sonar-auth-aad/files/3385828/Logs.zip)

Please let us know incase of any info from our end.

Regards

**Comment by julienlancelot** [comment] 2019-07-12 10:00
This issue seems to come from this ERROR message : 

```
2019.07.12 14:47:00 INFO  web[][c.m.a.a.AuthenticationAuthority] [Correlation ID: 66b75288-196e-4ce1-83b5-5db181d1e010] Instance discovery was successful
2019.07.12 14:47:21 ERROR web[][c.m.a.a.AuthenticationContext] [Correlation ID: 66b75288-196e-4ce1-83b5-5db181d1e010] Execution of class com.microsoft.aad.adal4j.AcquireTokenCallable failed.
java.net.ConnectException: Connection timed out: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient$1.run(HttpClient.java:526)
	at java.base/sun.net.www.http.HttpClient$1.run(HttpClient.java:524)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:551)
	at java.base/sun.net.www.http.HttpClient.privilegedOpenServer(HttpClient.java:523)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:564)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1075)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1356)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1331)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:242)
	at com.microsoft.aad.adal4j.AdalOAuthRequest.configureHeaderAndExecuteOAuthCall(AdalOAuthRequest.java:145)
	at com.microsoft.aad.adal4j.AdalOAuthRequest.send(AdalOAuthRequest.java:83)
	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:86)
	at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:928)
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:70)
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:38)
	at com.microsoft.aad.adal4j.AdalCallable.call(AdalCallable.java:47)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

**Comment by v-haburr** [comment] 2019-07-12 10:07
Can we mitigate this issue from our end? Are they any steps/guidelines to be followed ? or is this the issue with plugin?
Just to make sure I am understanding correctly - is Azure AD Authentication works with java 11 or above version. Because we are not facing any issue when we tried to authenticate AAD with java 8 and sonar 7.8.

**Comment by julienlancelot** [comment] 2019-07-12 10:20
this issue is not coming from the plugin but from AAD, so I let AAD experts investigate and help you !

**Comment by v-haburr** [comment] 2019-07-12 11:44
Thanks for your quick replies,
Can we expect any timeline for this to solve? As we were stuck with our migration

**Comment by srvrguy** [comment] 2019-07-12 17:28
Quick response, as I'm currently caught up in another project. (This plugin is a volunteer thing for me at the least.)

I haven't had issues with SonarQube 7.9 and the plugin. I just upgraded to 7.9.1 from 7.9.0 without incident. I'm running on Ubuntu 18.04 LTS with OpenJDK 11.0.3.

As soon as I get a chance, I'll review the logs in full.

**Comment by srvrguy** [comment] 2019-07-12 18:36
Looking at the logs, it certainly seems to be some kind of issue with a connection timeout to Microsoft's servers. There's a lot of possibilities for why that may be happening, and unfortunately since it's a timeout, not a lot of detail. I can try to reproduce it, but I'll need you to provide details on the configuration you're using so I can replicate the setup as much as possible.

Also, just to be safe, try accessing the following URLs from the server where SonarQube 7.9 is running:

* https://login.microsoftonline.com/common/oauth2/authorize
* https://graph.microsoft.com/v1.0/

You'll get error messages displayed at both of those, but that's fine. Just make sure the site loads on the server.

**Comment by v-haburr** [comment] 2019-07-12 19:09
May I know which configuration details are required in detail. So that I can provide them.
As pointed, I will hit the URL's in the server once.

**Comment by v-haburr** [comment] 2019-07-12 19:14
JFYI, 
1. when we run sonar 7.8 and java 8 version the authentication works fine.
2. When we run sonar 7.8 and java 11+ version as explained by you we are getting timeout exception similarly for 7.9 LTS.
Is this because of java version?

**Comment by srvrguy** [comment] 2019-07-12 20:10
It certainly seems something is different with the Java version.

So, to start, what OS are you using for the SonarQube server? What DB engine (name and version) are you using? That's probably not relevant, but it helps me target what to reproduce. What exact version of Java are you using (for both 8 and 11)? Are you using the official Oracle downloads, the AdoptOpenJDK version, or something else? What install method are you using for the Java install (full offline, web install, chocolatey, or something else)? Are you connecting to the SonarQube software directly, or are you going through a reverse proxy like IIS, nginx, or similar? Do you have any non-standard security setup, like disabling trust in certain certificate root authorities or a scanning SSL proxy server in the middle?

**Comment by v-haburr** [comment] 2019-07-13 04:13
1. what OS are you using for the SonarQube server -- **Windows server 2012**
2. What DB engine (name and version) -- **SQL Server 2014**
3. What exact version of Java are you using (for both 8 and 11) -- **jdk11.0.3/jdk12.0.1**
4. Are you using the official Oracle downloads-- **Yes**
5. What install method are you using for the Java install-- **Web install**
6. Are you connecting to the SonarQube software directly? -- **going through a reverse proxy in IIS**
7. Do you have any non-standard security setup-- **No**

**Comment by srvrguy** [comment] 2019-07-13 05:56
I'll try to replicate as soon as I can.

**Comment by v-haburr** [comment] 2019-07-13 06:21
Thanks Michael for such a prompt response.

Will be awaiting for your feedback

**Comment by srvrguy** [comment] 2019-07-13 19:34
Since it's the weekend, I don't have time for a full replication, but I took time this morning to run some tests.

I used Windows Server 2016 version 1607 and MSSQL 2017 (14.0) to test, and made sure that I was using IIS for reverse proxying.

For the process, I did a clean install of SonarQube 7.8 running on Java 8u201 and installed the plugin from the marketplace link. After configuring it, I confirmed that login via MS Account (AAD) worked. Group sync also worked. I then removed the old Java version and installed Java 11u3 direct from Oracle. I configured SonarQube 7.9.1 to use the same database and ran the upgrade process. Login from MS Account (AAD) worked. Group sync worked.

So far, I cannot reproduce this issue. If I have more time, I'll try with the exact specs you gave. Right now, I'd suggest if you have the resources to try a clean install of SonarQube on a clean VM/server and check if the problem exists on that install.

**Comment by v-haburr** [comment] 2019-07-16 03:57
I tried with a new empty data base and tried to authenticate still we encounter the same issue.

**Comment by mishra1010** [comment] 2019-07-16 04:41
@srvguy - Please let us know if a desktop sharing session would help in this case to show the environment.

**Comment by v-haburr** [comment] 2019-07-18 05:58
@srvrguy  hope you are doing great. Any update over our issue. If required, we can have a screen share and work on .

**Comment by v-haburr** [comment] 2019-07-22 05:32
@srvrguy we were stuck with our upgrade to sonarqube 7.9 LTS due to AAD authentication issue. Can you help on our request.

**Comment by naveenkumarmca** [comment] 2019-07-25 07:07
Hey @julienlancelot is there any work around or alternavetive apporach is there to proceed to use AAD in SonarQube 7.9.1. We are struck here.

**Comment by srvrguy** [comment] 2019-07-25 16:37
I've done tests on Windows Server 2012 and still haven't been able to replicate the behavior. As far as I can tell, there must be something specific to your setup.

One thing you can try is running a tool that will help diagnose connection issues. You could try downloading [SocketTest](http://sockettest.sourceforge.net/) on the problem server and run it. It's a Java tool that will attempt raw socket connections and even let you know if there is a certificate issue. If you want to try that, I can write up some quick instructions on how to use it, if needed.

**Comment by mishra1010** [comment] 2019-07-25 17:29
ok, Please let us know the steps. We can try running the tool and update you.

**Comment by srvrguy** [comment] 2019-07-25 22:32
Download the SocketTest binary from http://sockettest.sourceforge.net/ and extract the contents. Move the SocketTest.jar file from the dist directory to the server.

In a shell (either cmd or PowerShell) on the server:
 - cd to directory where you placed the jar
 - If you want to confirm java version you are using, run "java -version"
 - Run "java -jar SocketTest.jar"
 - In the client tab, you'll put in the details of the website you'll be testing against.
 - For "IP Address", put in the DNS name of the server you'll be trying. See list below.
 - For "Port", use 443. Make sure the "Secure" checkbox is checked.
 - Once entered, you can click on the "Connect" button.
 - Use the Send section to send the following messages (remove the quotes):
     - "GET / HTTP/1.1"
     - "Host: SERVERNAME" (Use the DNS name of the server you put in above)
     - "" (Send a blank line)
 - If all goes well, you'll get back some HTML in the box above.
 
 
Servers to try:
 - login.microsoftonline.com
 - graph.microsoft.com

**Comment by naveenkumarmca** [comment] 2019-07-26 09:29
Hi @srvrguy , We did these steps. But getting exception during connect itself. Adding log and screen shot.
[Socket test error log.log](https://github.com/hkamel/sonar-auth-aad/files/3435138/Socket.test.error.log.log)
![Socket test error](https://user-images.githubusercontent.com/42217814/61941849-e5bfbb80-afb5-11e9-8d54-964f2ef23eae.png)

**Comment by naveenkumarmca** [comment] 2019-07-26 10:02
@srvrguy  Hi, Adding an information, We are using Windows 2012 R2 server

**Comment by hkamel** [comment] 2019-07-26 18:23
You don't need to connect to the machine itself on 443, you need to test the connectivity to the servers that we need for the login process:
- login.microsoftonline.com
- graph.microsoft.com

![image](https://user-images.githubusercontent.com/5002831/61972981-f98a1280-aff3-11e9-9e8b-4398cdb357ae.png)

**Comment by srvrguy** [comment] 2019-07-26 18:43
You also want to make sure that secure checkbox is checked so you can try the communication part if it does connect.

**Comment by hkamel** [comment] 2019-07-26 18:44
All, looking into the comments and the findings and my understanding is that the issue happens when  Java 11+ is benign used with the plugin.

sonar-auth-aad plugin is relying on Microsoft Azure Active Directory Authentication Library (ADAL) for Java which currently doesn't support Java 11+ and no plans to support it, please check [Not able to Build ADAL4J library with Java 11 #238](https://github.com/AzureAD/azure-activedirectory-library-for-java/issues/238)

Microsoft is investing in a new library [MSAL4J](https://github.com/AzureAD/microsoft-authentication-library-for-java), which is the new client MS Identity client library for Java, and has all ADAL4J features and more does support Java 11. 

This requires refactoring/rewrite the plugin to utilize the new library.

**Comment by srvrguy** [comment] 2019-07-26 18:51
The weird thing is that I tested on various Windows versions with Java 11 and haven't had the same issues. Likewise, I have it running fine at my office on Java 11 with Linux and no issues. I'm guessing that even though you can't build the source for ADAL on 11, the binaries work fine in most of the circumstances where I've been able to test.

**Comment by naveenkumarmca** [comment] 2019-07-30 03:52
Hi @hkamel , Thanks for the update,
Currently in AAD plug in AadIdentityProvider refers to ADAL4J for ClientCredential, UserIdentity.Builder etc for context.authenticate() . Is there any details or steps available to do the same with the help of MSAL4J, Because When I'm trying to replace ADAL4J jar with MSAL4J , some of these classes are not there . Can you please help us on this .

**Comment by srvrguy** [comment] 2019-07-30 04:19
MSAL4J is not a drop-in replacement for ADAL4J. It will possibly take a bunch of code re-work once MSAL4J is in a more stable state. You can't just replace the JAR files.

I still highly suggest trying the existing plugin on a clean VM. I can't reproduce your issue on any of the configurations I've tried, and we're using Java 11 with the plugin perfectly fine at my primary job.

**Comment by naveenkumarmca** [comment] 2019-07-30 04:41
Hi @srvrguy , We have connected to login.microsoftonline.com,graph.microsoft.com as discussed earlier. When we send message as following 
1. GET / HTTP/1.1 gives nothing but connection will be alive.
2. But for all other messages we are getting following response and gets disconnected.

HTTP/1.1 400 Bad Request
Content-Type: text/html; charset=us-ascii
Server: Microsoft-HTTPAPI/2.0
Date: Mon, 29 Jul 2019 04:42:11 GMT
Connection: close
Content-Length: 326

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid Verb</h2>
<hr><p>HTTP Error 400. The request verb is invalid.</p>
</BODY></HTML>

**Comment by alaincroisetiere** [comment] 2019-08-09 13:01
Hi guys, same issue occure in my case when user is not allowed to sign in Azure Active Directory application.

![image](https://user-images.githubusercontent.com/12752936/62780599-14449880-ba84-11e9-9cf2-b44e35d32ad9.png)

error=access_denied
error_description=AADSTS650056: Misconfigured application. This could be due to one of the following: The client has not listed any permissions for 'AAD Graph' in the requested permissions in the client's application registration. Or, The admin has not consented in the tenant. Or, Check the application identifier in the request to ensure it matches the configured client application identifier. Please contact your admin to fix the configuration or consent on behalf of the tenant.

**Comment by srvrguy** [comment] 2019-08-09 14:32
@naveenkumarmca I'm not sure how much further I can help you. I've done a bunch of tests and can't reproduce your issue. No matter the version of Windows, I can't get a timeout to happen. I can only suggest you try installing SonarQube and this plugin on a new VM and testing there.

@alaincroisetiere Slightly different issue on your end. In your case, it looks like you turned on group sync but haven't approved the permissions needed for that to work. Try turning off group sync and see if the basic login functions. If you need the feature, then check the Group Sync page on the project wiki and make sure all the steps are complete, including the permission grant. If you can't get it working, please create a new issue.

**Comment by gvstsai** [comment] 2019-08-19 11:35
@v-haburr 
Is the reported AAD authentication issue resolved? We would like to know below listed points which will help in our SonarQube Server upgrade to 7.9.1  plan.. Thanks in advance.                                                                                                                                                       1. From which version you had tried to upgrade SonarQube 7.9.1 LTS?                                                                                                                                                         2. How many hours took in completing the  DB migration activity?                                                        3. What was your MLOC size ?

**Comment by srvrguy** [comment] 2019-08-24 20:56
I don't know if @v-haburr was ever able to get their issue resolved, but I have not been able to reproduce the problem.

For my primary job, we're using SQ 7.9.1 on Ubuntu 18.04 LTS (Azure VM) with OpenJDK 11.0.4 and PostgreSQL. The plugin works quite fine for us, and we're in and out nearly every workday. I generally keep the install updated, and we've been using it since the 5.3 release. We only have about 700 KLOC across two projects.

I've also tested this plugin against SQ 7.9.1 on fresh updated installs of Windows Server 2012 and 2016 editions using the Oracle JDK 11 and the built-in H2 DB and have had no issues with the plugin. I didn't test against the AdoptOpenJDK distribution.

**Comment by mishra1010** [comment] 2019-08-25 06:38
@srvrguy - This issue still exists and we are evaluating SAML auth to overcome this for the Sonar upgrade.

**Comment by shawnzhu88** [comment] 2019-11-07 20:01
Got the same issue (403 - Forbidden) after login with Azure Active Directory. I am running Sonarqube v7.9.1 Community edition docker image within Azure AKS. Log level set to DEBUG and no message related to this 403 error. The AAD registered app was given permission for User.Read and User.ReadBasic.All.  After login, any page (/about, /projects/favorite, etc) will throw 403 and nothing shows up in logs.

**Comment by andybochmann** [comment] 2019-11-08 19:14
I seem to be having the exact same issue as well, running the SonarQube 8.0 Bitnami VM image in Azure.

**Comment by srvrguy** [comment] 2019-11-08 19:58
That's interesting. I'm wondering if it's related to the images. I usually do a manual setup and don't see those problems. I'll try to look into this soon.

**Comment by shawnz88** [comment] 2019-11-09 16:50
Reverted to Sonarqube 7.8 docker image from 7.9.1 docker image on Azure AKS and got the exact same error. So it's not related to Java 11. My AKS setup has an Application Gateway and Nginx Ingress Controller in front of Sonarqube. Whenever click on the "Sign in with Azure AAD" and the AAD login page shows up and even before putting in any credential, i am getting "403 -Forbidden" if I open another tab within the browser and try to reach the sonarqube homepage. The only way to get back to the site is either clearing up all cookies or wait for couple of minutes until some kind of timeout occurs. Seems to me that there is a oauth related cookie is set when you click the "login with AAD" which prevents access to the site and this cookie is not being reset after successful login.

**Comment by shawnz88** [comment] 2019-11-11 20:47
Another observation for sonarqube v7.9.1:  In IE11 (does't work with Edge or Chrome), if you wait for 5 minutes after you login and gets 403-Forbidden, refresh the page and you will be in.

**Comment by nimeshkb** [comment] 2019-11-14 12:19
I am getting Authentication related error (401) while trying with Sonarqube 7.9LTS EE, this is working fine with Sonarqube 7.7LTS EE

**Comment by srvrguy** [comment] 2019-11-14 20:08
There seem to be a lot of different configurations in here, which is making it hard for me to reproduce the issue. Please, everyone on here, add a comment with the details of your configuration so I can try to get as close as possible and see if I can reproduce. In some cases, I may not be able to, but I can try to get close.

For my general testing during development, I primarily use the following setup:

- Apple macOS 10.15.1
- OpenJDK 11.0.2 (64-bit) - For running SQ
- SonarQube Community 7.9.1 and 8.0
- No proxy used for local testing

For further testing/use, I have the following environments:

Main Use:
- Ubuntu 18.04 LTS (Azure VM)
- OpenJDK 11.0.4 (64-bit) provided in Ubuntu
- SonarQube Community Edition 7.9.1 (currently)
- Nginx HTTPS Reverse Proxy

Test Config 1:
- Windows Server 2016 (via VMWare)
- Oracle JDK 11
- SonarQube Community Edition 7.9
- IIS HTTPS Reverse Proxy

Test 2:
- Windows 10
- Oracle JDK 11
- SonarQube Community Edition 7.9
- No proxy used for local testing

At the present moment, I cannot reproduce any of the issues in any of the environments. I've also tried the Bitnami SonarQube 8 VM appliance, and had no issues. I'll keep trying other configurations and version changes as I get the time.

For the 403 issues after signing in, I am wondering if there is some issue in the reverse proxy config. I'd suggest looking at the logs there as a start.

**Comment by shawnz88** [comment] 2019-11-14 22:07
Found out the root cause: the Azure Application WAF in front of Nginx Ingress Controller is blocking some of the redirects during login. After changing the WAF to Detection mode instead of Prevention mode, it worked like a charm. Haven't figured out what rule triggered the blocking yet.

**Comment by srvrguy** [comment] 2019-11-14 23:29
That's great to hear! I'm still going to try and pin down some other configurations just to make sure I'm doing the best I can at checking configurations.

**Comment by andybochmann** [comment] 2019-11-15 00:43
I got the Bitnami SonarQube 8 VM working today. I used my AAD email address on the administrator account and apparently it didn't like that. After changing the email address on the administrator account, I was able to log in.

**Comment by christopher-scolt** [comment] 2019-12-11 07:10
I ran into (what appeared to be) the same issue with my environment (v8 hosted in Azure).  I found that this problem went away when I disabled **Groups Synchronization**.

HTH

**Comment by srvrguy** [comment] 2019-12-11 18:59
I wonder if that's a big part of the issue. If you would like to help with the group sync issue you're seeing, please open a new issue and I'll try to help figure out what's going wrong in that part.

**Comment by srvrguy** [comment] 2020-02-13 19:15
This should be working with the 1.2.0 release now. If the issue continues, feel free to reply and I can re-open the issue.

**Closed by srvrguy** 2020-02-13 19:15 UTC
Labels: under investigation
