### ISSUE TITLE
Support for ADAL ends June 30th, 2023

### ISSUE THREAD

**Issue by eeisenbr** [hkamel/sonar-auth-aad#153] opened 2023-03-30 15:03 UTC
https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-migration
https://learn.microsoft.com/en-us/azure/active-directory/develop/migrate-adal-msal-java

It's not strictly necessary, but should probably replace ADAL with MSAL soon.

**Comment by srvrguy** [comment] 2023-03-30 17:05
I'm very aware of the end of life for ADAL. It is being dropped in the next major release as soon as I can get the time to do the very few minor things remaining. It will not be replaced with MSAL, however, for a few reasons:

- MSAL is overkill for what this project needs. It's mainly just doing a one-off auth. MSAL is focused heavily on maintaining auth for tools that interact extensively with MS.
- For some reason, MSAL just won't work properly in the plugin. There are some odd classloader issues when I plug it in, and because of the prior reason I don't think it's worth trying to find the cause.
- MSAL, because of how it's designed, is complex to work with for just basic authentication.

The alternative is moving to using the Nimbus OAuth SDK directly. MSAL uses this library at the core, actually. Using the SDK directly provides a lightweight solution for handling authentication that's less complex than MSAL. You can check out the work on the branch named "develop".

**Closed as completed by srvrguy** 2023-03-30 17:05 UTC
